http:
  routers:
    router-chobase:
      rule: "HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.example.com`)"
      entryPoints: ["websecure"]
      service: "service-chobase"
      tls:
        certResolver: letsencrypt
        domains:
          - main: "chobase.com"
            sans: ["*.chobase.com"]
    router2:
      rule: "HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.example.net`)"
      # ... 유사한 설정
    router3:
      rule: "HostRegexp(`{subdomain:[a-zA-Z0-9-]+}.example.org`)"
      # ... 유사한 설정
