global:
  checkNewVersion: true
  sendAnonymousUsage: true

api:
  dashboard: true

entryPoints:
  ssh:
    address: ":22"
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    swarmMode: true
    exposedByDefault: false
    network: traefik-public

certificatesResolvers:
  let:
    acme:
      email: "your-email@example.com"
      storage: "/acme/acme.json"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1"
          - "1.0.0.1"